#!/bin/bash -e

exec {DB}<> /dev/tcp/"${DB_HOST:=172.17.0.2}"/"${DB_PORT:=6379}"
function cleanup {
    exec {DB}>&-
    exec {DB}<&-
}
trap cleanup EXIT

function get {
    echo "RPOP $@" >&$DB
    read -u $DB count
    [[ "${count:1:-1}" -le 0 ]] && return
    read -u $DB -r -N ${count:1:-1}
    echo $REPLY | gpg -d -
}

function set {
    echo "LPUSH $1 '$(gpg -r $1 -qae -)'"
} >&$DB

[[ "$(type -t $1)" == function ]] && "$@"